- name: pypi-publish
  # You may pin to the exact commit or the version.
  # uses: pypa/gh-action-pypi-publish@717ba43cfbb0387f6ce311b169a825772f54d295
  uses: pypa/gh-action-pypi-publish@v1.5.0
  with:
    # PyPI user
    user: # optional, default is __token__
    # Password for your PyPI user or an access token
    password: secrets.PYPI_API_TOKEN
    # The repository URL to use
    repository_url: # optional
    # The target directory for distribution
    packages_dir: # optional, default is dist
    # Check metadata before uploading
    verify_metadata: # optional, default is true
    # Do not fail if a Python package distribution exists in the target package index
    skip_existing: # optional
    # Show verbose output.
    verbose: # optional
    # Show hash values of files to be uploaded
    print_hash: # optional
